// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrU0dULq_NVR4dKAi1CEMP_e6s8cXUq_8',
    appId: '1:135333490351:web:275357d1b3c5e0f51b6e5a',
    messagingSenderId: '135333490351',
    projectId: 'flutter-chat-a95ed',
    authDomain: 'flutter-chat-a95ed.firebaseapp.com',
    databaseURL: 'https://flutter-chat-a95ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chat-a95ed.firebasestorage.app',
    measurementId: 'G-ZJE8VVRCZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2A5mnXbLB8HtFaEY0BYwerXntQIjYYpY',
    appId: '1:135333490351:android:ae7279834abbb4bf1b6e5a',
    messagingSenderId: '135333490351',
    projectId: 'flutter-chat-a95ed',
    databaseURL: 'https://flutter-chat-a95ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chat-a95ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw1DS-9f8LdTp6_C6EOoJ642gxSKli5qw',
    appId: '1:135333490351:ios:61e2f7b8ccd118131b6e5a',
    messagingSenderId: '135333490351',
    projectId: 'flutter-chat-a95ed',
    databaseURL: 'https://flutter-chat-a95ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chat-a95ed.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
